version: '3.8'

services:
  app:
    image: mtichy22/nette-app:latest
    volumes:
      - .:/var/www
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: postgres:16.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'

volumes:
  db_data: